#My first pipeline with GitHub actions

name: myGithubActions_basics

on:
   push:
    branches: [ "master"]
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print hello message in testing
      run: echo "Hello from testing job"
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print hello message in deploy
      run: echo "Hello from deploy job"

