#My first pipeline with GitHub actions

name: myGithubActions_basics

env:
  APPLICATION_NAME: "Myflask"
  DEPLOY_PACKAGE_NAME: "flask_deploy_ver-${{ github.sha }}"

on:
   push:
    branches: [ "master"]
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print hello message in testing
      run: echo "Hello from testing job"
      
    - name: Execute few commands
      run: |
        echo "message 1"
        echo "message 2"
        echo "Application name: ${{ env.APPLICATION_NAME }}"
        
     
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folder
      run: ls -la
      
    - name: Test some packages if there are present
      run: aws --version
      
    - name: Test some packages if there are present
      run: zip --version
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    env:
      VAR1: "This is job level variable1"
    
    steps:
    - name: Print hello message in deploy
      run: echo "Hello from deploy job"
      
    - name: Print hello message in deploy
      run: |
        echo "Var1 = ${{ env.VAR1 }}"
        echo "Var2 = ${{ env.VAR2 }}"
        echo "ver3 = $LOCAL_VAR"
      env:
        LOCAL_VAR: "This is step level local variable"
      
    - name: Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
