#My first pipeline with GitHub actions

name: myGithubActions_basics

env:
  APPLICATION_NAME: "Myflask"
  DEPLOY_PACKAGE_NAME: "flask_deploy_ver-${{ github.sha }}"

on:
   push:
    branches: [ "master"]
    
jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print hello message in testing
      run: echo "Hello from testing job"
      
    - name: Execute few commands
      run: |
        echo "message 1"
        echo "message2"
        echo "Application name: ${{ env.APPLICATION_NAME }}
      
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print hello message in deploy
      run: echo "Hello from deploy job"
      
    - name: Deployment package
      run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
